export const engineeringColleges: string[] = [
  "Brindavan College of Engineering",
  "Jain College of Engineering, BELGAUM",
  "Cambridge Institute of Technology",
  "VTU Extension Center, Bangalore",
  "IMPACT SCHOOL OF ARCHITECTURE",
  "GIRIJABAI SAIL INSTITUTE OF TECHNOLOGY, Haliyal",
  "Government Engineering College",
  "Sir M Visvesvaraya Institute of Technology",
  "Basaveshwar Engineering College, Bagalkot",
  "Amrutha Institute of Engineering & Management",
  "Dayananda Sagar College of Engineering",
  "Government Engineering College",
  "East West Institute of Technology,",
  "Dr. Timmaiah Institute of Technology, Kolar",
  "Maharaja Institute of Technology, Mysore",
  "Smt. Kamala & Sri Venkappa M Agadi Institute of Engineering & Technology",
  "Mysore college of Engineering",
  "Ballari Institute of Technology & Management",
  "PES College of Engineering, Mandya",
  "New Horizon College of Engineering,",
  "KS School of Engineering & Management,",
  "ATME College of Engineering,",
  "KCT Engineering College, Gulbarga",
  "Islamiah Inst. of Technology, BANGALORE",
  "Rajeev Institute of Technology,",
  "BGS Institute of Technology, Mandya District",
  "Veerappa Nisty Engineering College",
  "SDM College of Engineering & Technology, Dharwad",
  "HMS SCHOOL OF ARCHITECTURE",
  "Vishwanathrao Deshpande Institute of Technology",
  "NDRK Institute of Technology, HASSAN",
  "PES Institute of Technology & Management, Shivamogga",
  "RL Jalappa Institute of Technology, Doddaballapur",
  "Govt. Engineering College,",
  "G MADEGOWDA INSTITUTE OF TECHNOLOGY",
  "MV J College of Engineering, Bangalore",
  "Bapuji Institute of Engineering & Technology, Davangere",
  "Govt. SKSJ Technological Institute, Bangalore",
  "Govt. Engineering College,",
  "HKBK College of Engineering, Bangalore",
  "LINGARAJ APPA ENGINEERING COLLEGE",
  "Govt. Engineering College,",
  "P A College of Engineering, MANGALORE",
  "BASAV ENGINEERING SCHOOL OF TECHNOLOGY",
  "Dr. Sri Sri Sri Shivakumara Mahaswamy Institute of Engineering & Technology",
  "SDM Institute of Technology, UJIRE",
  "BILURU GURUBASAVA MAHASWAMIJI INSTITUTE OF TECHNOLOGY",
  "Appa Institute of Engineering & Technology, Gulbarga",
  "PDA College of Engineering,",
  "MYSORE SCHOOL OF ARCHITECTURE",
  "Govt. Engineering College,",
  "Sri Sairam College of Engineering, Bangalore",
  "Akshaya Institute of Technology, Tumkur",
  "Sri Basaveshwara Institute of Technology",
  "Gopalan College of Engineering & Management, Bangalore",
  "Jain Acharya Gundharnandi Maharaj",
  "JAIN COLLEGE OF ENGINEERING, Bangalore",
  "Nitte School of Architecture",
  "BTL Institute of Technology Management,",
  "MANGALORE MARINE COLLEGE AND INSTITUTE",
  "Alvas Institute of Engineering and Technology",
  "R R Institute of Technology, BANGALORE",
  "BNM Institute of Technology, BANGALORE",
  "Cambridge Institute of Technology, Bangalore",
  "VTU Extension Centre, IR Rasta, Bangalore",
  "Bearys Institute of Technology,",
  "Canara Engineering College,",
  "Bangalore College of Engineering & Technology",
  "Proudadevaraya Institute of Technology, Hospet",
  "Shree Devi Institute of Technology, Mangalore",
  "GSSS Institute of Engineering & Technology for Women, Mysore",
  "Guru Nanak Dev Engineering College",
  "AMC Engineering College,",
  "BMS SCHOOL OF ARCHITECTURE",
  "Sir M V School of Architecture, Bangalore",
  "Gogte Institute of Technology, BELGAUM",
  "Ekalavya Institute of Technology, Chamarajanagar",
  "MS Engineering College, Bangalore",
  "Sahyadri College of Engineering & Management",
  "Sambhram Institute of Technology, Bangalore",
  "Vemana Institute of Technology, Bangalore",
  "Basava Kalyan Engineering College, Bidar",
  "Nitte Meenakshi Institute of Technology, Bangalore",
  "Dayananda Sagar College of Architecture",
  "Rajiv Gandhi Institute of Technology,",
  "ANJUMAN INSTITUTE OF TECHNOLOGY, Bhatkal",
  "JYOTHY INSTITUTE OF TECHNOLOGY, Bangalore",
  "Shah-Shib College of Engineering, Bidar",
  "Govt. Tool Room & Training Centre",
  "Vidya Vardhaka College of Engineering, Mysore",
  "Govt. Engineering College,",
  "JNN College of Engineering, Shivamogga",
  "T. John Institute of Technology, Bangalore",
  "Jnana Vikas Institute of Technology, Bidadi",
  "Bangalore Technological Institute, Bangalore",
  "Govt. Engineering College,",
  "KLES College of Engineering & Technology, Belgaum",
  "The Oxford College of Engineering, Bangalore",
  "JSS Academy of Technical Education, Bangalore",
  "City Engineering College, Bangalore",
  "Rao Bahaddur Y Mahabaleshwarappa Engineering College",
  "Kalpataru Institute of Technology, Tiptur",
  "CMR Institute of Technology, BANGALORE",
  "MAHARAJA INSTITUTE OF TECHNOLOGY, Mysore",
  "Malik Sandal Institute of Arts & Architecture, Gulbarga",
  "G M Institute of Technology, DAVANGERE",
  "BGS SCHOOL OF ARCHITECTURE",
  "K L E S College of Engineering & Technology, Chikodi",
  "Hirasugar Institute of Technology, Nidasoshi",
  "Sri Venkateshwara College of Engineering, Bangalore",
  "SJM Institute of Technology, CHITRADURGA",
  "BLDE Association's College of Engineering & Technology, Vijayapura",
  "KV G College of Engineering, Sullia",
  "EAST WEST SCHOOL OF ARCHITECTURE",
  "UBDT College of Engineering, Davangere",
  "SJB Institute of Technology, BANGALORE",
  "National Institute of Engineering, Mysore",
  "SG Balekundri Institute of Technology, Belgaum",
  "VS M Institute of Technology, Nipani",
  "KB N College of Engineering, Gulbarga",
  "YENEPOYA INSTITUTE OF TECHNOLOGY, Mangalore",
  "Vidya Vikas Institute of Technology, Mysore",
  "Siddaganga Institute of Technology, Tumkur",
  "AGM Rural College of Engineering & Technology",
  "Sri Revana Siddeshwara Institute of Technology",
  "Malnad College of Engineering, Hassan",
  "Govt. SKS J Technological Institute(Evening), Bangalore",
  "ACS College of Engineering, BANGALORE",
  "R V College of Engineering, BANGALORE",
  "EAST WEST COLLEGE OF ENGINEERING",
  "Aditya Academy of Architecture & Design",
  "GOVERNMENT ENGINEERING COLLEGE, Haveri",
  "GODUTAI ENGINEERING COLLEGE FOR WOMEN, Gulbarga",
  "GOPALAN SCHOOL OF ARCHITECTURE",
  "H.K.E. Society's S.L.N. College of Engineering, Raichur",
  "Adichunchanagiri Institute of Technology, Chikkamagaluru",
  "Bhemanna Khandre Institute of Technology, Bhalki",
  "Don Bosco Institute of Technology,",
  "PESIT-Bangalore South",
  "Visvesvaraya Technological University, Belgaum",
  "A J Institute of Engineering and Technology, Mangalore",
  "RNS Institute of Technology, BANGALORE",
  "Atria Institute of Technology, BANGALORE",
  "MS Ramaiah Institute of Technology,",
  "RR School of Architecture, BANGALORE",
  "KNS Institute of Technology, BANGALORE",
  "Tontadarya College of Engineering,",
  "Moodalkatte Institute of Technology,",
  "Govt. Engineering College,",
  "Srinivas School of Engineering,",
  "KLE Institute of Technology, HUBLI",
  "Acharya Institute of Technology,",
  "C. Bairegouda Institute of Technology,",
  "JAIN INSTITUTE OF TECHNOLOGY,",
  "Coorg Institute of Technology, PONNAMPET",
  "BMS (Even) College of Engineering,",
  "Acharyar NRV School of Architecture,",
  "Raja Rajesheshwari College of Engineering,",
  "K S Institute of Technology, BANGALORE",
  "Mangalore Institute of Technology & Engineering",
  "Karavali Institute of Technology, Mangalore",
  "Visvesvaraya Technological University,",
  "Sri Krishna Institute of Technology, Bangalore",
  "Visvesvaraya Technological University,",
  "Wadiyar Centre For Architecture, Mysore",
  "Bangalore Institute of Technology,",
  "Rural Engineering College, Hulkoti",
  "Impact College of Engineering & Applied Sciences",
  "Alpha College of Engineering, Bangalore",
  "Navodaya Institute of Technology, Raichur",
  "Govt. Engineering College,",
  "BMS Institute of Technology & Management, Bangalore",
  "HONEYWELL TECHNOLOGIES SOLUTIONS INDIA",
  "BMS College of Architecture,",
  "R V Institute of Technology and Management, Bangalore",
  "S J C Institute of Technology, CHICKBALLAPUR",
  "Global Academy of Technology",
  "NIE Institute of Technology, MYSORE",
  "Sampoorna Institute of Technology & Research",
  "Srinivas Institute of Technology, Mangalore",
  "SJB SCHOOL OF ARCHITECTURE",
  "Vijaya Vittal Institute of Technology, Bangalore",
  "East Point College of Engineering & Technology, Bangalore",
  "VTU Extension Centre, United Mission, Bangalore",
  "Shri Madhwa Vadiraja Institute of Technology & Management",
  "Angadi Institute of Technology & Management, Belgaum",
  "SHREE VINAYAKA INSTITUTE OF TECHNOLOGY",
  "DAYANANDA SAGAR ACADEMY OF TECHNOLOGY AND MANAGEMENT",
  "Maratha Mandal Engineering College",
  "Vivekananda College of Engineering & Technology, Puttur",
  "JAIN COLLEGE OF ENGINEERING, Belgaum",
  "Vivekananda Institute of Technology, Bangalore",
  "APS College of Engineering, Bangalore",
  "National Institute of Engineering, Mysore",
  "Govt. Engineering College,",
  "SHETTY INSTITUTE OF TECHNOLOGY, Gulbarga",
  "ST JOSEPH ENGINEERING COLLEGE, Mangalore",
  "BMS College of Engineering, Bangalore",
  "HMS Institute of Technology, TUMKUR",
  "NMAM Institute of Technology, Nitte",
  "SECAB Institute of Engineering & Technology, Vijayapura",
  "Govt. Tool Room & Training Centre",
  "ST J Institute of Technology, Ranebennur",
  "RV COLLEGE OF ARCHITECTURE",
  "CAUVERY INSTITUTE OF TECHNOLOGY, Mandya",
  "Ghousia College of Engineering,",
  "Shaikh College of Engineering & Technology, Belgaum",
  "Sai Vidya Institute of Technology, Bangalore",
  "Sapthagiri College of Engineering, Bangalore",
  "Visvesvaraya Technological University,",
  "Bahubali College of Engineering, Gommata Nagar",
  "MYSURU ROYAL INSTITUTE OF TECHNOLOGY",
  "Dr. Ambedkar Institute of Technology, Bangalore",
  "Channabasaveshwara Institute of Technology, Gubbi",
  "Shridevi Institute of Engineering & Technology, Tumkur",
  "Nagarjuna College of Engineering & Technology, Bangalore",
  "RNS SCHOOL OF ARCHITECTURE",
  "V.T.U Extension Center, NMAIT, Nitte",
  "KS SCHOOL OF ARCHITECTURE",
  "SEA College of Engineering & Technology, Bangalore"
];