export const engineeringColleges: string[] = [
  "A J Institute of Engineering and Technology, Mangalore",
  "Acharya Institute of Technology,",
  "ACS College of Engineering, BANGALORE",
  "Adichunchanagiri Institute of Technology, Chikkamagaluru",
  "AGM Rural College of Engineering & Technology",
  "Akshaya Institute of Technology, Tumkur",
  "Alpha College of Engineering, Bangalore",
  "Alvas Institute of Engineering and Technology",
  "AMC Engineering College,",
  "Amrutha Institute of Engineering & Management",
  "Angadi Institute of Technology & Management, Belgaum",
  "ANJUMAN INSTITUTE OF TECHNOLOGY, Bhatkal",
  "Appa Institute of Engineering & Technology, Gulbarga",
  "APS College of Engineering, Bangalore",
  "ATME College of Engineering,",
  "Atria Institute of Technology, BANGALORE",
  "Bahubali College of Engineering, Gommata Nagar",
  "Ballari Institute of Technology & Management",
  "Bangalore College of Engineering & Technology",
  "Bangalore Institute of Technology,",
  "Bangalore Technological Institute, Bangalore",
  "Bapuji Institute of Engineering & Technology, Davangere",
  "Basava Kalyan Engineering College, Bidar",
  "Basaveshwar Engineering College, Bagalkot",
  "Bearys Institute of Technology,",
  "BGS Institute of Technology, Mandya District",
  "Bhemanna Khandre Institute of Technology, Bhalki",
  "BILURU GURUBASAVA MAHASWAMIJI INSTITUTE OF TECHNOLOGY",
  "BLDE Association's College of Engineering & Technology, Vijayapura",
  "BMS College of Engineering, Bangalore",
  "BMS (Even) College of Engineering,",
  "BMS Institute of Technology & Management, Bangalore",
  "BNM Institute of Technology, BANGALORE",
  "Brindavan College of Engineering",
  "BTL Institute of Technology Management,",
  "Cambridge Institute of Technology",
  "Cambridge Institute of Technology, Bangalore",
  "Canara Engineering College,",
  "CAUVERY INSTITUTE OF TECHNOLOGY, Mandya",
  "C. Bairegouda Institute of Technology,",
  "Channabasaveshwara Institute of Technology, Gubbi",
  "City Engineering College, Bangalore",
  "CMR Institute of Technology, BANGALORE",
  "Coorg Institute of Technology, PONNAMPET",
  "DAYANANDA SAGAR ACADEMY OF TECHNOLOGY AND MANAGEMENT",
  "Dayananda Sagar College of Engineering",
  "Don Bosco Institute of Technology,",
  "Dr. Ambedkar Institute of Technology, Bangalore",
  "Dr. Sri Sri Sri Shivakumara Mahaswamy Institute of Engineering & Technology",
  "Dr. Timmaiah Institute of Technology, Kolar",
  "East Point College of Engineering & Technology, Bangalore",
  "EAST WEST COLLEGE OF ENGINEERING",
  "East West Institute of Technology,",
  "Ekalavya Institute of Technology, Chamarajanagar",
  "Ghousia College of Engineering,",
  "GIRIJABAI SAIL INSTITUTE OF TECHNOLOGY, Haliyal",
  "Global Academy of Technology",
  "G MADEGOWDA INSTITUTE OF TECHNOLOGY",
  "G M Institute of Technology, DAVANGERE",
  "GODUTAI ENGINEERING COLLEGE FOR WOMEN, Gulbarga",
  "Gogte Institute of Technology, BELGAUM",
  "Gopalan College of Engineering & Management, Bangalore",
  "Government Engineering College",
  "GOVERNMENT ENGINEERING COLLEGE, Haveri",
  "Govt. Engineering College,",
  "Govt. SKSJ Technological Institute, Bangalore",
  "GSSS Institute of Engineering & Technology for Women, Mysore",
  "Guru Nanak Dev Engineering College",
  "Hirasugar Institute of Technology, Nidasoshi",
  "HKBK College of Engineering, Bangalore",
  "H.K.E. Society's S.L.N. College of Engineering, Raichur",
  "HMS Institute of Technology, TUMKUR",
  "Impact College of Engineering & Applied Sciences",
  "Islamiah Inst. of Technology, BANGALORE",
  "Jain Acharya Gundharnandi Maharaj",
  "JAIN COLLEGE OF ENGINEERING, Bangalore",
  "Jain College of Engineering, BELGAUM",
  "JAIN COLLEGE OF ENGINEERING, Belgaum",
  "JAIN INSTITUTE OF TECHNOLOGY,",
  "Jnana Vikas Institute of Technology, Bidadi",
  "JNN College of Engineering, Shivamogga",
  "JSS Academy of Technical Education, Bangalore",
  "JYOTHY INSTITUTE OF TECHNOLOGY, Bangalore",
  "Kalpataru Institute of Technology, Tiptur",
  "Karavali Institute of Technology, Mangalore",
  "KB N College of Engineering, Gulbarga",
  "KCT Engineering College, Gulbarga",
  "KLE Institute of Technology, HUBLI",
  "KLES College of Engineering & Technology, Belgaum",
  "K L E S College of Engineering & Technology, Chikodi",
  "KNS Institute of Technology, BANGALORE",
  "K S Institute of Technology, BANGALORE",
  "KV G College of Engineering, Sullia",
  "LINGARAJ APPA ENGINEERING COLLEGE",
  "Maharaja Institute of Technology, Mysore",
  "MAHARAJA INSTITUTE OF TECHNOLOGY, Mysore",
  "Malnad College of Engineering, Hassan",
  "Mangalore Institute of Technology & Engineering",
  "MANGALORE MARINE COLLEGE AND INSTITUTE",
  "Maratha Mandal Engineering College",
  "Moodalkatte Institute of Technology,",
  "MS Engineering College, Bangalore",
  "MS Ramaiah Institute of Technology,",
  "MV J College of Engineering, Bangalore",
  "Mysore college of Engineering",
  "MYSURU ROYAL INSTITUTE OF TECHNOLOGY",
  "Nagarjuna College of Engineering & Technology, Bangalore",
  "National Institute of Engineering, Mysore",
  "Navodaya Institute of Technology, Raichur",
  "NDRK Institute of Technology, HASSAN",
  "New Horizon College of Engineering,",
  "NIE Institute of Technology, MYSORE",
  "Nitte Meenakshi Institute of Technology, Bangalore",
  "NMAM Institute of Technology, Nitte",
  "P A College of Engineering, MANGALORE",
  "PDA College of Engineering,",
  "PES College of Engineering, Mandya",
  "PES Institute of Technology & Management, Shivamogga",
  "PESIT-Bangalore South",
  "Proudadevaraya Institute of Technology, Hospet",
  "Raja Rajesheshwari College of Engineering,",
  "Rajeev Institute of Technology,",
  "Rajiv Gandhi Institute of Technology,",
  "Rao Bahaddur Y Mahabaleshwarappa Engineering College",
  "RL Jalappa Institute of Technology, Doddaballapur",
  "RNS Institute of Technology, BANGALORE",
  "R R Institute of Technology, BANGALORE",
  "Rural Engineering College, Hulkoti",
  "R V College of Engineering, BANGALORE",
  "R V Institute of Technology and Management, Bangalore",
  "Sahyadri College of Engineering & Management",
  "Sai Vidya Institute of Technology, Bangalore",
  "Sambhram Institute of Technology, Bangalore",
  "Sampoorna Institute of Technology & Research",
  "Sapthagiri College of Engineering, Bangalore",
  "SDM College of Engineering & Technology, Dharwad",
  "SDM Institute of Technology, UJIRE",
  "SEA College of Engineering & Technology, Bangalore",
  "SECAB Institute of Engineering & Technology, Vijayapura",
  "SG Balekundri Institute of Technology, Belgaum",
  "Shah-Shib College of Engineering, Bidar",
  "Shaikh College of Engineering & Technology, Belgaum",
  "SHETTY INSTITUTE OF TECHNOLOGY, Gulbarga",
  "Shree Devi Institute of Technology, Mangalore",
  "SHREE VINAYAKA INSTITUTE OF TECHNOLOGY",
  "Shridevi Institute of Engineering & Technology, Tumkur",
  "Shri Madhwa Vadiraja Institute of Technology & Management",
  "Siddaganga Institute of Technology, Tumkur",
  "Sir M Visvesvaraya Institute of Technology",
  "SJB Institute of Technology, BANGALORE",
  "S J C Institute of Technology, CHICKBALLAPUR",
  "SJM Institute of Technology, CHITRADURGA",
  "Smt. Kamala & Sri Venkappa M Agadi Institute of Engineering & Technology",
  "Sri Basaveshwara Institute of Technology",
  "Sri Krishna Institute of Technology, Bangalore",
  "Srinivas Institute of Technology, Mangalore",
  "Sri Revana Siddeshwara Institute of Technology",
  "Sri Sairam College of Engineering, Bangalore",
  "Sri Venkateshwara College of Engineering, Bangalore",
  "ST J Institute of Technology, Ranebennur",
  "ST JOSEPH ENGINEERING COLLEGE, Mangalore",
  "The Oxford College of Engineering, Bangalore",
  "T. John Institute of Technology, Bangalore",
  "Tontadarya College of Engineering,",
  "UBDT College of Engineering, Davangere",
  "Veerappa Nisty Engineering College",
  "Vemana Institute of Technology, Bangalore",
  "Vidya Vardhaka College of Engineering, Mysore",
  "Vidya Vikas Institute of Technology, Mysore",
  "Vijaya Vittal Institute of Technology, Bangalore",
  "Vishwanathrao Deshpande Institute of Technology",
  "Visvesvaraya Technological University,",
  "Visvesvaraya Technological University, Belgaum",
  "Vivekananda College of Engineering & Technology, Puttur",
  "Vivekananda Institute of Technology, Bangalore",
  "VS M Institute of Technology, Nipani",
  "YENEPOYA INSTITUTE OF TECHNOLOGY, Mangalore",
  "Acharyar NRV School of Architecture,",
  "Aditya Academy of Architecture & Design",
  "BASAV ENGINEERING SCHOOL OF TECHNOLOGY",
  "BGS SCHOOL OF ARCHITECTURE",
  "BMS College of Architecture,",
  "BMS SCHOOL OF ARCHITECTURE",
  "Dayananda Sagar College of Architecture",
  "EAST WEST SCHOOL OF ARCHITECTURE",
  "GOPALAN SCHOOL OF ARCHITECTURE",
  "Govt. SKS J Technological Institute(Evening), Bangalore",
  "Govt. Tool Room & Training Centre",
  "HMS SCHOOL OF ARCHITECTURE",
  "HONEYWELL TECHNOLOGIES SOLUTIONS INDIA",
  "IMPACT SCHOOL OF ARCHITECTURE",
  "KS SCHOOL OF ARCHITECTURE",
  "KS School of Engineering & Management,",
  "Malik Sandal Institute of Arts & Architecture, Gulbarga",
  "MYSORE SCHOOL OF ARCHITECTURE",
  "Nitte School of Architecture",
  "RNS SCHOOL OF ARCHITECTURE",
  "RR School of Architecture, BANGALORE",
  "RV COLLEGE OF ARCHITECTURE",
  "Sir M V School of Architecture, Bangalore",
  "SJB SCHOOL OF ARCHITECTURE",
  "Srinivas School of Engineering,",
  "VTU Extension Center, Bangalore",
  "V.T.U Extension Center, NMAIT, Nitte",
  "VTU Extension Centre, IR Rasta, Bangalore",
  "VTU Extension Centre, United Mission, Bangalore",
  "Wadiyar Centre For Architecture, Mysore",
  "Other College"
];
