import {
  SiPython,
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiNodedotjs,
  SiDjango,
  SiFlask,
  SiRubyonrails,
  SiExpress,
  SiSpringboot,
  SiPostgresql,
  SiMongodb,
  SiMysql,
  SiSqlite,
  SiRedis,
  SiAmazon, // Corrected
  SiGooglecloud,
  SiVercel,
  SiNetlify,
  SiDocker,
  SiKubernetes,
  SiGit,
  SiLinux,
  SiTerraform,
  SiTensorflow,
  SiPytorch,
  SiGraphql,
  SiGo,
  SiRust,
  SiKotlin,
  SiSwift,
  SiPhp,
  SiRuby,
  SiFlutter,
  SiFigma,
  SiAdobexd,
  SiSketch,
  SiInvision,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiAdobepremierepro,
  SiAdobeaftereffects,
  SiBlender,
  SiGooglesheets,
  SiNotion,
  SiJira,
  SiTrello,
  SiAsana,
  SiSlack,
  SiMiro,
  SiAirtable,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
} from "react-icons/si";

import {
  FaJava,
  FaDatabase,
  FaSyncAlt,
  FaCode,
  FaShieldAlt,
  FaLink,
  FaTasks,
  FaChartBar,
  FaFileInvoiceDollar,
  FaCalculator,
  FaCogs,
  FaBullhorn,
  FaSearchDollar,
  FaGlobe,
  FaTags,
  FaBoxOpen,
  FaHandshake,
  FaChess,
  FaUsers,
  FaUserPlus,
  FaAddressBook,
  FaShippingFast,
  FaChartPie,
  FaPalette,
  FaPaintBrush,
  FaVideo,
  FaPencilAlt,
  FaObjectGroup,
  FaCube,
  FaComments,
  FaUserTie,
  FaClock,
  FaLightbulb,
  FaBrain,
  FaRandom,
  FaMicrophone,
  FaSmile,
  FaChalkboardTeacher,
  FaFistRaised,
  FaHeart,
  FaFileExcel,
  FaFilePowerpoint,
  FaFileWord,
  FaRobot,
  FaNetworkWired,
  FaServer,
} from "react-icons/fa";

import { VscAzure } from "react-icons/vsc";

import { type IconType } from "react-icons";

const skillIconMap: Record<string, IconType> = {
  // Technical
  Python: SiPython,
  Java: FaJava,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  HTML: SiHtml5,
  CSS: SiCss3,
  React: SiReact,
  "Next.js": SiNextdotjs,
  Vue: SiVuedotjs,
  Angular: SiAngular,
  Svelte: SiSvelte,
  "Node.js": SiNodedotjs,
  Django: SiDjango,
  Flask: SiFlask,
  "Ruby on Rails": SiRubyonrails,
  "Express.js": SiExpress,
  "Spring Boot": SiSpringboot,
  SQL: FaDatabase,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  MySQL: SiMysql,
  SQLite: SiSqlite,
  Redis: SiRedis,
  AWS: SiAmazon,
  Azure: VscAzure,
  "Google Cloud": SiGooglecloud,
  Vercel: SiVercel,
  Netlify: SiNetlify,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  Git: SiGit,
  Linux: SiLinux,
  "CI/CD": FaSyncAlt,
  Terraform: SiTerraform,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  "Scikit-learn": SiScikitlearn,
  "Machine Learning": FaRobot,
  Pandas: SiPandas,
  NumPy: SiNumpy,
  GraphQL: SiGraphql,
  "REST API": FaNetworkWired,
  gRPC: FaServer,
  Go: SiGo,
  Rust: SiRust,
  Kotlin: SiKotlin,
  Swift: SiSwift,
  PHP: SiPhp,
  Ruby: SiRuby,
  "C#": FaCode,
  "C++": FaCode,
  C: FaCode,
  "React Native": SiReact,
  Flutter: SiFlutter,
  Cybersecurity: FaShieldAlt,
  Blockchain: FaLink,

  // Business
  "Project Management": FaTasks,
  Agile: FaSyncAlt,
  Scrum: FaSyncAlt,
  "Business Analysis": FaChartBar,
  Finance: FaFileInvoiceDollar,
  Accounting: FaCalculator,
  Operations: FaCogs,
  Marketing: FaBullhorn,
  "Market Research": FaSearchDollar,
  "Digital Marketing": FaGlobe,
  Sales: FaTags,
  "Product Management": FaBoxOpen,
  "Business Development": FaHandshake,
  Strategy: FaChess,
  "Human Resources": FaUsers,
  Recruiting: FaUserPlus,
  "Customer Relationship Management (CRM)": FaAddressBook,
  "Supply Chain Management": FaShippingFast,
  "Data Analysis": FaChartPie,
  Negotiation: FaHandshake,

  // Creative
  "UI/UX Design": FaPalette,
  Figma: SiFigma,
  "Adobe XD": SiAdobexd,
  Sketch: SiSketch,
  InVision: SiInvision,
  "Graphic Design": FaPaintBrush,
  Photoshop: SiAdobephotoshop,
  Illustrator: SiAdobeillustrator,
  "Video Editing": FaVideo,
  "Premiere Pro": SiAdobepremierepro,
  "After Effects": SiAdobeaftereffects,
  "Content Writing": FaPencilAlt,
  "User Research": FaUsers,
  Wireframing: FaObjectGroup,
  Prototyping: FaObjectGroup,
  "3D Modeling": FaCube,
  Blender: SiBlender,

  // SoftSkills
  Communication: FaComments,
  Leadership: FaUserTie,
  Teamwork: FaUsers,
  "Time Management": FaClock,
  "Problem Solving": FaLightbulb,
  "Critical Thinking": FaBrain,
  Creativity: FaLightbulb,
  Adaptability: FaRandom,
  "Public Speaking": FaMicrophone,
  "Emotional Intelligence": FaSmile,
  Collaboration: FaHandshake,
  Mentoring: FaChalkboardTeacher,
  "Conflict Resolution": FaFistRaised,
  Empathy: FaHeart,

  // Productivity
  "Microsoft Excel": FaFileExcel,
  PowerPoint: FaFilePowerpoint,
  Word: FaFileWord,
  "Google Sheets": SiGooglesheets,
  Notion: SiNotion,
  Jira: SiJira,
  Trello: SiTrello,
  Asana: SiAsana,
  Slack: SiSlack,
  Miro: SiMiro,
  Airtable: SiAirtable,
};

export function getSkillIcon(skillName: string): IconType | null {
  return skillIconMap[skillName] || null;
}
